CREATE TABLE IF NOT EXISTS InventoryManager (
    ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    PASSWORD VARCHAR(20) NOT NULL,
    NAME     VARCHAR(30) NOT NULL,
    AGE      INT,
    GENDER   TEXT,
    PHONE    TEXT,
    POSITION TEXT
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_ID       TEXT PRIMARY KEY,
    PRODUCT_TYPE     VARCHAR(20) NOT NULL,
    PRODUCT_NAME     VARCHAR(20) NOT NULL,
    PRODUCT_PRICE    DOUBLE      NOT NULL,
    PRODUCT_QUANTITY INT         NOT NULL
);

CREATE TRIGGER IF NOT EXISTS createProductId
    AFTER INSERT
    ON PRODUCT
BEGIN
    UPDATE PRODUCT
    SET PRODUCT_ID = PRINTF('P%05d', new.oid)
    WHERE oid = new.ROWID;
END;

CREATE TABLE IF NOT EXISTS SUPPLIER (
    SUPPLIER_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    SUPPLIER_NAME     VARCHAR(50) NOT NULL ,
    CONTACT_NO        TEXT NOT NULL,
    ADDRESS           TEXT         NOT NULL ,
    EMAIL             TEXT         NOT NULL
);

CREATE TABLE IF NOT EXISTS PURCHASE_ORDER (
    PURCHASE_ORDER_NUMBER INT NOT NULL ,
    SUPPLIER_ID           INT NOT NULL,
    PRODUCT_ID            TEXT NOT NULL,
    QUANTITY              INT     NOT NULL,
    ORDER_DATE            DATE    NOT NULL,
    PRICE                 INT     NOT NULL,
    PRIMARY KEY (PURCHASE_ORDER_NUMBER, SUPPLIER_ID, PRODUCT_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS RETAILER (
    RETAILER_ID  INTEGER PRIMARY KEY AUTOINCREMENT,
    LOCATION    VARCHAR(100) NOT NULL,
    CONTACT_NO  VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS RETURN_ORDER (
    RETURN_ID     INT,
    SUPPLIER_ID   INT,
    PRODUCT_ID    TEXT,
    QUANTITY      INT  NOT NULL,
    RETURN_DATE   DATE NOT NULL,
    RETURN_REASON VARCHAR(200),
    PRIMARY KEY (RETURN_ID, SUPPLIER_ID, PRODUCT_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS STOCK_RETURN (
    RETURN_ID   INT   INTEGER,
    RETAILER_ID INT  NOT NULL,
    PRODUCT_ID  TEXT  NOT NULL,
    QUANTITY    INT  NOT NULL,
    RETURN_DATE DATE NOT NULL,
    PRIMARY KEY (RETURN_ID,RETAILER_ID, PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    FOREIGN KEY (RETAILER_ID) REFERENCES RETAILER (RETAILER_ID)
);

CREATE TABLE IF NOT EXISTS StockTransfer (
    PRODUCT_ID        TEXT  NOT NULL,
    RETAILER_ID       INT  NOT NULL,
    TRANSFER_QUANTITY INT  NOT NULL,
    TRANSFER_DATE     DATE NOT NULL,
    PRIMARY KEY (PRODUCT_ID, RETAILER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    FOREIGN KEY (RETAILER_ID) REFERENCES RETAILER (RETAILER_ID)
);
