DROP TABLE IF EXISTS InventoryManager;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS PURCHASE_ORDER;
DROP TABLE IF EXISTS RETAILER;
DROP TABLE IF EXISTS RETURN_ORDER;
DROP TABLE IF EXISTS STOCK_RETURN;
DROP TABLE IF EXISTS StockTransfer;
